name: myecommerce
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^1.0.1
  dots_indicator: ^2.0.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_storage: ^8.1.0
  provider: ^5.0.0
  geolocator: ^7.0.3
  geocoder: ^0.2.1
  google_maps_flutter: ^2.0.5
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.6
  carousel_slider: ^3.0.0
  paginate_firestore:
  persistent_bottom_nav_bar: ^4.0.2
  url_launcher: ^6.0.6
  map_launcher: ^2.0.0
  expandable_text: ^2.2.0
  flutter_easyloading: ^3.0.0
  toggle_bar: ^1.0.0
  dotted_border: ^2.0.0
  chips_choice: ^2.0.1
  stripe_payment: ^1.1.3
  flutter_credit_card: ^2.0.0
  http: ^0.13.3
  flutter_slidable: ^0.6.0
  search_page: ^2.0.0+1
  getwidget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Regular.ttf

    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
